services:
  - type: web
    name: form-submission-app
    env: python
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "alembic upgrade head && uvicorn api.main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: ENV
        value: production

