"""Added new table, changed table name

Revision ID: 4b1e42782278
Revises: 0ff358d0bcd7
Create Date: 2024-12-07 14:23:09.166555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b1e42782278'
down_revision: Union[str, None] = '0ff358d0bcd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bankmobile_form_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('current_school_email', sa.String(length=100), nullable=False),
    sa.Column('current_school_email_pass', sa.String(length=50), nullable=False),
    sa.Column('previous_school_email', sa.String(length=100), nullable=False),
    sa.Column('previous_school_email_pass', sa.String(length=50), nullable=False),
    sa.Column('bankmobile_email', sa.String(length=100), nullable=False),
    sa.Column('bankmobile_email_pass', sa.String(length=50), nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bankmobile_form_submissions_id'), 'bankmobile_form_submissions', ['id'], unique=False)
    op.create_table('school_form_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('current_school_email', sa.String(length=100), nullable=False),
    sa.Column('current_school_email_pass', sa.String(length=50), nullable=False),
    sa.Column('previous_school_email', sa.String(length=100), nullable=False),
    sa.Column('previous_school_email_pass', sa.String(length=50), nullable=False),
    sa.Column('bankmobile_email', sa.String(length=100), nullable=True),
    sa.Column('bankmobile_email_pass', sa.String(length=50), nullable=True),
    sa.Column('student_id', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_school_form_submissions_id'), 'school_form_submissions', ['id'], unique=False)
    op.drop_index('ix_form_submissions_id', table_name='form_submissions')
    op.drop_table('form_submissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_submissions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('current_school_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('current_school_email_pass', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('previous_school_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('previous_school_email_pass', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bankmobile_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bankmobile_email_pass', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='form_submissions_pkey')
    )
    op.create_index('ix_form_submissions_id', 'form_submissions', ['id'], unique=False)
    op.drop_index(op.f('ix_school_form_submissions_id'), table_name='school_form_submissions')
    op.drop_table('school_form_submissions')
    op.drop_index(op.f('ix_bankmobile_form_submissions_id'), table_name='bankmobile_form_submissions')
    op.drop_table('bankmobile_form_submissions')
    # ### end Alembic commands ###
