"""Added phone number

Revision ID: 740fdb496b2b
Revises: 
Create Date: 2024-12-07 20:44:59.718289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '740fdb496b2b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bankmobile_form_submissions', sa.Column('phone', sa.String(length=50), nullable=False, server_default=''))
    op.add_column('school_form_submissions', sa.Column('phone', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school_form_submissions', 'phone')
    op.drop_column('bankmobile_form_submissions', 'phone')
    # ### end Alembic commands ###
