"""Another migration

Revision ID: c895dde2d66a
Revises: 30f5a52dac43
Create Date: 2024-12-03 02:45:14.446557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c895dde2d66a'
down_revision: Union[str, None] = '30f5a52dac43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_submissions', sa.Column('name', sa.String(), nullable=False))
    op.add_column('form_submissions', sa.Column('current_school_email', sa.String(), nullable=False))
    op.add_column('form_submissions', sa.Column('current_school_email_pass', sa.String(), nullable=False))
    op.add_column('form_submissions', sa.Column('previous_school_email', sa.String(), nullable=False))
    op.add_column('form_submissions', sa.Column('previous_school_email_pass', sa.String(), nullable=False))
    op.add_column('form_submissions', sa.Column('bankmobile_email', sa.String(), nullable=False))
    op.add_column('form_submissions', sa.Column('bankmobile_email_pass', sa.String(), nullable=False))
    op.add_column('form_submissions', sa.Column('student_id', sa.String(), nullable=False))
    op.add_column('form_submissions', sa.Column('date_of_birth', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_submissions', 'date_of_birth')
    op.drop_column('form_submissions', 'student_id')
    op.drop_column('form_submissions', 'bankmobile_email_pass')
    op.drop_column('form_submissions', 'bankmobile_email')
    op.drop_column('form_submissions', 'previous_school_email_pass')
    op.drop_column('form_submissions', 'previous_school_email')
    op.drop_column('form_submissions', 'current_school_email_pass')
    op.drop_column('form_submissions', 'current_school_email')
    op.drop_column('form_submissions', 'name')
    # ### end Alembic commands ###
